# Generated by Django 3.1.3 on 2023-08-26 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0002_auto_20230826_1352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='chocies',
        ),
        migrations.AddField(
            model_name='submission',
            name='choices',
            field=models.ManyToManyField(to='onlinecourse.Choice'),
        ),
    ]
