# Generated by Django 3.1.3 on 2023-08-26 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0003_auto_20230826_1903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='choices',
        ),
        migrations.AddField(
            model_name='submission',
            name='choice',
            field=models.ManyToManyField(to='onlinecourse.Choice'),
        ),
    ]
